---
abstract: 'calculate the Levenshtein edit distance between two strings'
author:
  - 'Dree Mistrut <dree@friul.it>'
  - 'Josh Goldberg <jgoldberg@cpan.org>'
  - 'Neil Bowers <neilb@cpan.org>'
build_requires:
  Test::More: '0.88'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Levenshtein
requires:
  Carp: '0'
  Exporter: '0'
  List::Util: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Text-Levenshtein
  repository: https://github.com/neilbowers/Text-Levenshtein.git
version: '0.08'
